name: unison-to-markdown
license: BSD3
default-extensions:

  # Notable

  - StrictData

  # Other

  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

ghc-options: -Wall
dependencies:

  # Notable

  - hashable
  - unison-parser-typechecker

  # Other

  - base
  - bytestring
  - containers
  - filepath
  - text
  - unordered-containers

library:
  source-dirs: src

executables:
  unison-to-markdown:
    source-dirs: .
    main: Main.hs
    ghc-options: -threaded -rtsopts
    dependencies:
      - gitrev
      - optparse-applicative
      - unison-to-markdown

tests:
  spec:
    source-dirs: test
    main: Test.hs
    dependencies:
      - hspec
      - unison-to-markdown
